spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/projectdb
    username: projectuser
    password: qwerty123

springdoc:
  packages-to-scan:
    - web.tech.project
  paths-to-match:
    - "/api/**"